# chotot-cli - command-line client and price analyser for Chợ Tốt.
# Copyright (C) 2026 V
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
# Affero General Public License <https://www.gnu.org/licenses/> for details.

"""Category-specific search facets.

Chợ Tốt exposes far more than keyword and price: phones filter by brand,
capacity and colour; cars by make, model, gearbox, fuel, seats and year; property
by rooms, direction and legal status. These live in
``chotot/data/facets.json``, generated by ``tools/build_facets.py``.

Each facet records whether it was **verified to filter**. That distinction is
the point: the posting-form schema declares ``elt_warranty`` and
``elt_cellular_type`` exactly like the working ones, and the gateway accepts both
with HTTP 200 while ignoring them. Offering an unverified facet as a filter
would hand the user an unfiltered result set labelled as filtered, so this module
only ever exposes the verified ones.
"""
from __future__ import annotations

import difflib
from functools import lru_cache
from typing import Any, Dict, List, Optional, Tuple

from chotot.errors import UsageError
from chotot.taxonomy import _load, categories, normalise


@lru_cache(maxsize=None)
def _all() -> Dict[str, Dict[str, Any]]:
    try:
        return _load("facets.json").get("facets", {})
    except Exception:  # noqa: BLE001 - facets are optional enrichment
        return {}


def snapshot_date() -> str:
    try:
        return _load("facets.json").get("fetched_at", "unknown")
    except Exception:  # noqa: BLE001
        return "unknown"


def _works(spec: Dict[str, Any]) -> bool:
    verified = spec.get("verified")
    return bool(verified and verified.get("works"))


def for_category(category_id: Optional[int], only_working: bool = True) -> Dict[str, Dict[str, Any]]:
    """Facets available for a category, walking up to its parent when needed."""
    if category_id is None:
        return {}
    entry = _all().get(str(category_id), {})
    if not entry:
        parent = (categories().get(str(category_id)) or {}).get("parent")
        if parent is not None:
            entry = _all().get(str(parent), {})
    if not only_working:
        return dict(entry)
    return {name: spec for name, spec in entry.items() if _works(spec)}


def codes_collide_with_labels(spec: Dict[str, Any]) -> bool:
    """True when a raw code could be mistaken for a label of the same facet."""
    options = spec.get("options") or {}
    labels = {str(v).strip().casefold() for v in options.values()}
    return any(str(code).casefold() in labels for code in options)


def describe(category_id: int) -> List[Dict[str, Any]]:
    """Rows for ``chotot facets <category>``."""
    rows = []
    for name, spec in sorted(for_category(category_id).items()):
        rows.append({
            "param": name,
            "label": spec.get("label") or name,
            "is_range": bool(spec.get("is_range")),
            "options": spec.get("options") or {},
            # e.g. `carseats`, whose labels are numbers that collide with the
            # codes. Values are resolved by label there, so a raw code is not
            # a reliable way to address it.
            "use_labels_not_codes": codes_collide_with_labels(spec),
        })
    return rows


def _resolve_option(spec: Dict[str, Any], value: str) -> str:
    """Turn a human label into the code the gateway wants.

    Accepts, in decreasing strictness: the exact label, the numeric code, an
    accent-folded label ('apple', 'tu dong'), the same ignoring spaces
    ('256GB'), and finally a substring. The first strictness level that yields
    ANY candidate decides, and ambiguity there is refused in one place.

    Why refusing matters: ``normalise`` drops punctuation, so ``'> 256 GB'`` and
    ``'256 GB'`` fold to the same key. Returning whichever came first filtered
    on "exactly 256GB" when the user asked for more -- and the gateway would
    have answered 200 either way.

    Why the exact LABEL outranks the code: a few facets have labels that are
    themselves numbers and collide with the codes. ``carseats`` is labelled
    "2", "4", "7" while its codes are 5, 1, 3, so ``carseats=4`` means four
    seats in every reading a user has. The codes exist only because the facets
    listing exposes them in JSON, and :func:`codes_collide_with_labels` flags
    such facets so the CLI can say a raw code is unreliable there.
    """
    options: Dict[str, str] = spec.get("options") or {}
    text = str(value).strip()
    folded = normalise(text)
    squashed = folded.replace(" ", "")
    field = spec.get("label") or spec.get("param") or "this facet"

    # Progressively looser matchers. The first that matches anything decides.
    strategies = (
        ("exact label", lambda label: label.strip().casefold() == text.casefold()),
        ("code", None),  # handled separately: keys, not values
        ("folded label", lambda label: normalise(label) == folded),
        ("spacing-insensitive label", lambda label: normalise(label).replace(" ", "") == squashed),
        ("partial label", lambda label: bool(folded) and folded in normalise(label)),
    )

    for name, predicate in strategies:
        if predicate is None:
            if text in options:
                return text
            continue
        candidates = [code for code, label in options.items() if predicate(label)]
        if len(candidates) == 1:
            return candidates[0]
        if len(candidates) > 1:
            shown = ", ".join(repr(options[c]) for c in candidates[:6])
            distinct = {options[c].strip().casefold() for c in candidates}
            if len(distinct) == 1:
                # Upstream lists one label under several codes (cg=14050 has
                # "Midea" as both 4 and 9). Nothing the user types separates
                # them, so name the codes instead of picking one.
                raise UsageError(
                    f"{value!r} is listed under {len(candidates)} codes of "
                    f"'{field}': {', '.join(sorted(candidates))}.",
                    remedy=f"Pass the numeric code instead, e.g. "
                           f"{spec.get('param', 'facet')}={sorted(candidates)[0]}.",
                )
            raise UsageError(
                f"{value!r} matches {len(candidates)} options of '{field}': {shown}.",
                remedy="Type the label exactly as shown by 'chotot facets <category>'.",
            )

    close = difflib.get_close_matches(folded, [normalise(v) for v in options.values()],
                                      n=4, cutoff=0.5)
    hint = f" Closest: {', '.join(close)}." if close else ""
    sample = list(options.values())[:8]
    raise UsageError(
        f"{value!r} is not a valid value for '{field}'.{hint}",
        remedy=f"Valid values include: {', '.join(sample)}"
               + (" ..." if len(options) > 8 else "")
               + ". Run 'chotot facets <category>' for the full list.",
    )


def parse(category_id: Optional[int], pairs: List[str]) -> Dict[str, Any]:
    """Turn ``--facet brand=apple --facet year=2019-2021`` into query parameters.

    Raises:
        UsageError: unknown facet, unknown option, or a facet the gateway is
            known to ignore.
    """
    if not pairs:
        return {}
    available = for_category(category_id)
    if not available:
        raise UsageError(
            "No verified facets are available for this category."
            if category_id else "--facet needs --category so the facet can be resolved.",
            remedy="Run 'chotot facets <category>' to see what is supported.",
        )

    resolved: Dict[str, Any] = {}
    for pair in pairs:
        if "=" not in pair:
            raise UsageError(f"--facet expects name=value, got {pair!r}.",
                             remedy="For example: --facet mobile_brand=apple")
        name, _, value = pair.partition("=")
        name, value = name.strip(), value.strip()

        spec = available.get(name)
        if spec is None:
            # Allow the human label as the facet name too ('Hãng' or 'hang').
            for candidate, candidate_spec in available.items():
                if normalise(candidate_spec.get("label") or "") == normalise(name):
                    name, spec = candidate, candidate_spec
                    break
        if spec is None:
            unverified = for_category(category_id, only_working=False).get(name)
            if unverified is not None:
                reason = (unverified.get("verified") or {}).get("reason", "not usable as a filter")
                raise UsageError(
                    f"'{name}' exists on this category but does not filter: {reason}.",
                    remedy="The gateway accepts it and returns unfiltered results. "
                           "Run 'chotot facets <category>' for facets that do work.",
                )
            close = difflib.get_close_matches(name, list(available), n=4, cutoff=0.4)
            raise UsageError(
                f"Unknown facet {name!r}." + (f" Did you mean: {', '.join(close)}?" if close else ""),
                remedy="Run 'chotot facets <category>' to list supported facets.",
            )

        if spec.get("is_range"):
            if "-" not in value:
                raise UsageError(
                    f"'{name}' is a range facet, so it needs MIN-MAX, got {value!r}.",
                    remedy=f"For example: --facet {name}=2019-2021. A single value is "
                           f"accepted by the gateway and silently ignored.",
                )
            resolved[name] = value
        else:
            resolved[name] = _resolve_option({**spec, "param": name}, value)
    return resolved


def supported_params(category_id: Optional[int]) -> List[str]:
    return sorted(for_category(category_id))
